### ISSUE TITLE
FEREQ

### ISSUE THREAD

**Issue by mohanor** [joydip007x/prisma-unify007x#2]
hello friend,

I tried to import schemas to handle interrelations, but it didn't work for me. Is there something missing?

**Comment by joydip007x** [comment]
Are you using Vs-Code?
If yes, <br>
1. Install [prisma-import](https://marketplace.visualstudio.com/items?itemName=ajmnz.prisma-import) Extension (for VS code)<br>
2.Disable Official [prisma](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma) Extension (for VS code)

Did you check that ? Let me know.
Also can you share relevant poritoin of the code ,

**Comment by mohanor** [comment]
I followed your instructions and it worked. Thank you very much.
