### ISSUE TITLE
Combine schema.prisma do not contain the datasource

### ISSUE THREAD

**Issue by reanzi** [joydip007x/prisma-unify007x#4]
**Situation**
I don't know if it's a bug or what, But I notices when I run  `npx prisma-multischema` all schemas from subschemas are combine fine in the main schema.prisma but the base.prisma content is not included; because in base.prisma is where I put datasource ; trying toa run `npx prisma db push` fails with error `A datasource block is missing in the Prisma schema file.`

**To Reproduce**
Just package's example is okay to try

**Expected behavior**
I expected `schema.prisma` file to contain datasource at the top as usual

The package is great.
Am I missing something or?

**Comment by joydip007x** [comment]
@reanzi , the behaviour you described is  truly unexpected.
Can you just check the followings - 

- Rewrite **base.prisma** , freshly ( Place Only **generator client** and **datasource db**  ) [ [Reference file](https://github.com/joydip007x/Prisma-MultiSchema/blob/main/prisma/subschemas/base.prisma) ]
- Install latest prisma-multischema
- Delete schema.prisma and regenerate using `npx prisma-multischema` 
- Run `npx prisma db push` from Project Root 

If still the issue occurs , can you please share the Generated **schema.prisma** file (through ideone/pastebin/etc) 
and also **base.prisma** too  ?

**Comment by joydip007x** [comment]
I diagnosed many time, and this case never occurs.
From your Comment , I Quote , If the "  **all schemas** from subschemas are combine fine in the main schema.prisma .... "  The **base.prisma** should work too.

Maybe you had  a an unexpected behaviour as i have demonstrated it in **a Blog**, **a Video**  & 2 other Git Repos on how to Use it
and i suggest to take a look in [Official Readme.](https://github.com/joydip007x/Prisma-MultiSchema/blob/main/README.md)

Closing this after 2weeks of Inactivity 😊
