### ISSUE TITLE
IDE support?

### ISSUE THREAD

**Issue by Martinsos** [joydip007x/prisma-unify007x#5]
Thanks for this useful package!

I haven't seen any mention of the IDE support in the docs. Since we have multiple prisma schema files, how does formatting / diagnostics / autocompletion work?

Would be great to mention this in the docs: if it works well, say that it does, if it doesn't, explain that it doesn't yet and what are the plans for it.

**Comment by joydip007x** [comment]
Great Question  @Martinsos .

I have mentioned  IDE Support [Here](https://github.com/joydip007x/Prisma-MultiSchema#dependencies-optional), for VsCode

All the diagnostics / autocompletion work's by default provided by Prisma ( Official  [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma)) .
And [prisma-import ](https://marketplace.visualstudio.com/items?itemName=ajmnz.prisma-import)( Mentioned as Optional Dependencies ) Handles "Import/Export" Relations mentioned in *.prisma files

**Formatting**  is handled with - provided by Default **Prisma Format** command .Every time the `npx prisma-multischema` is executed,[ npx prisma format runs behind the scene](https://github.com/joydip007x/Prisma-MultiSchema/tree/main#additional)

If i  missed anything, Feel free to ask 😀

**Comment by reanzi** [comment]
I works great; one thing though I noticed recently (till now), is whenever I work on any ```.prisma``` file, the ```schema.prisma``` get loaded on other tab by itself indicating it's unsaved.
Since we don't touch ```schema.prisma``` I find it annoying to need my attention.

Apart from that, good work guys 👍

**Comment by joydip007x** [comment]
Thank you  @reanzi , yours words are cheerfull.
Btw , the issue you are facing has something to do with **your IDE** settings : **File (Save/Unsave) Features** /**Enviroment Setting**.
**I assure you** `schema.prisma` popping up , is not configured in this package and this package  has nothing to do with that disturbance .
I suggest , you look around the `preferences` or `settings` in your IDE.
I am open to further discussion.

Thank you ❤️‍🔥

**Comment by Martinsos** [comment]
Thanks @joydip007x ! That clears it up. I still would suggest having a piece of docs where you explicitly address IDE support, in the sense that you describe what is supported and what is not compared to single-file prisma setup. Because I don't see that being mentioned right now -> you do mention what to add for better support, but don't explain what are the results.
So having a small section "IDE support" where you explain that to have full support one might need to install "prisma-import" VSCode extension and that then IDE support will be full -> that would be great.
