### ISSUE TITLE
'binaryTargets' inside 'generator client' throws error

### ISSUE THREAD

**Issue by erickriva** [joydip007x/prisma-unify007x#8]
**Describe the bug**
When adding `binaryTargets` property to `generate client`, a SyntaxError is thrown and generated `schema.prisma` is incomplete.

**To Reproduce**
- create a `base.prisma` file with following code:
  ```
  datasource db {
     provider = "mongodb"
     url      = env("DATABASE_URL")
  }

  generator client {
     provider      = "prisma-client-js"
     binaryTargets = ["native", "rhel-openssl-1.0.x"]
  }
  ```
- run `prisma-multischema` to generate final `schema.prisma`.

**Expected behavior**
'binaryTargets' should be included to 'generator client' in the generated `prisma.schema`.

**Version**
Latest stable, using `npx`.

**Docs**
[Prisma docs > Generators](https://www.prisma.io/docs/concepts/components/prisma-schema/generators#:~:text=the%20following%20generator%3A-,generator%20client%20%7B,%7D,-In%20that%20case)

**Screenshots**
![image](https://github.com/joydip007x/Prisma-MultiSchema/assets/2746558/d8b9a75c-dc0f-4b17-b8e8-8bc901a03ece)
![image](https://github.com/joydip007x/Prisma-MultiSchema/assets/2746558/2fb2dea2-ffa0-4b1a-8446-a2d8dc1fa96f)

**Comment by joydip007x** [comment]
Hey @erickriva 

I will look into it asap
..seems like an conditional error in logic was missed.

In the meantime,  If that's the line "binary Targets" is generating issue, just skip it in base.prisma. and Maybe adding it in generated file.

Sorry to suggest this way🥲
I will release it with recent fixes along the way.

**Comment by MSturges** [comment]
Yeah I'm having the same issue.  Love love the package tho, finally able to breakdown my 1,000 + line schema up for mysql db.  Prisma only supports a few db natively and need to flag it on, unfortunately mysql isn't one of them. 

I am unable to compile this bit of code here:

generator client {
  provider = "prisma-client-js"
  // Your local environment (from the logs) appears to be darwin-arm64 which is for Apple's M1 ARM64 architecture.
  // Vercel's environment requires rhel-openssl-1.0.x which is based on Red Hat Enterprise Linux with OpenSSL 1.0.x.
  binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin-arm64"]
}

gives me the following error: 

node_modules/prisma-multischema/lib/cjs/processor.js:138

                        if (line != '\n' && line != "" && logger_1.generatedComment.search(line) != -1) { }

                                                                                    ^



SyntaxError: Invalid regular expression: /  binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin-arm64"]/: Range out of order in character class



Perhaps we can add something like this to the code base:



function escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

if (line != '\n' && line != "" && logger_1.generatedComment.search(new RegExp(escapeRegExp(line))) != -1) { }

**Comment by joydip007x** [comment]
> Yeah I'm having the same issue. Love love the package tho, finally able to breakdown my 1,000 + line schema up for mysql db. Prisma only supports a few db natively and need to flag it on, unfortunately mysql isn't one of them.
> 
> I am unable to compile this bit of code here:
> 
> generator client { provider = "prisma-client-js" // Your local environment (from the logs) appears to be darwin-arm64 which is for Apple's M1 ARM64 architecture. // Vercel's environment requires rhel-openssl-1.0.x which is based on Red Hat Enterprise Linux with OpenSSL 1.0.x. binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin-arm64"] }
> 
> gives me the following error:
> 
> node_modules/prisma-multischema/lib/cjs/processor.js:138
> 
> ```
>                     if (line != '\n' && line != "" && logger_1.generatedComment.search(line) != -1) { }
> 
>                                                                                 ^
> ```
> 
> SyntaxError: Invalid regular expression: / binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin-arm64"]/: Range out of order in character class
> 
> Perhaps we can add something like this to the code base:
> 
> function escapeRegExp(string) { return string.replace(/[.*+?^${}()|[]\]/g, '\$&'); }
> 
> if (line != '\n' && line != "" && logger_1.generatedComment.search(new RegExp(escapeRegExp(line))) != -1) { }

Will  release the updated version soon(Withing 1 day)

**Comment by joydip007x** [comment]
@erickriva @MSturges 

Hi,
Check this release : https://www.npmjs.com/package/prisma-multischema/v/1.1.4

Update using : `npm i prisma-multischema@1.1.4`  

Check in your **package.json**'s  "prisma-multischema": version Entry

I believe that's fixed now
