### ISSUE TITLE
Shouldnt be writing on schema.prisma

### ISSUE THREAD

**Issue by Arkirion** [joydip007x/prisma-unify007x#9]
https://github.com/joydip007x/Prisma-MultiSchema/blob/79d0957f50b70783542ed0af324c4b5ffbc3dbf5/src/prismaUnify.ts#L71

Is true that this is a generated file, however I think it should not change if nothing was been changed on the splited files, update only date can be annoying, can we remove date and only left "dont edit this file, generated file" or something like that?

**Comment by joydip007x** [comment]
>update only date can be annoying, can we remove date and only left "dont edit this file, generated file" or something like that?

I agree with this part , but somehow kept it to make a gesture to the user who is updating different splitted files, so he knows
Last generated Schema time. 

If you still feel the need , Kindly change it to ( find the file in your project/packages/prisma-multischema)
`logStream.write('//🧩Don\'t Edit this Generated  file.✨✨\n'); `

( as i dont update this package very often, this tiny change should be stable in your repo )
